#! /usr/bin/env php
<?php 
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require 'vendor/autoload.php';

$app = new Application('Agência Escape Installer', '0.1');
$app->add(new Escape\Console\InstallCommand);
$app->run();